apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: minio-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      targetPort: http
    - name: console
      port: 9001
      targetPort: console
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: minio
