---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "false"
  exec.enabled: "true"
  url: https://argocd.assistants.ing.iaas.epita.fr
  dex.config: |
    connectors:
      - id: oidc_cri
        type: oidc
        name: CRI OIDC
        config:
          issuer: https://cri.epita.fr
          clientID: $oidc.clientID
          clientSecret: $oidc.clientSecret
          scopes:
            - openid
            - profile
            - roles
          promptType: none
          insecureEnableGroups: true
          requestedIDTokenClaims:
            roles:
              essential: true
          claimMapping:
            groups: roles
            email: preferred_username
