---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/nico34638/infra
    targetRevision: HEAD
    path: minikube/argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

