---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: minio
  project: default
  source:
    repoURL: https://github.com/nico34638/infra
    targetRevision: HEAD
    path: minikube/minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

