---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: vault
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.23.0
    helm:
      values: |
        fullnameOverride: vault
        global:
          enabled: true
          tlsDisable: false
        injector:
          enabled: false
        server:
          standalone:
            enabled: true
            config: |
              ui = true
              listener "tcp" {
                address = "[::]:8200"
                cluster_address = "[::]:8201"
                tls_cert_file = "/vault/userconfig/tls/tls.crt"
                tls_key_file = "/vault/userconfig/tls/tls.key"
                telemetry {
                  unauthenticated_metrics_access = true
                }
              }
              storage "file" {
                path = "/vault/data"
              }
          volumes:
            - name: tls
              secret:
                secretName: vault-tls
          volumeMounts:
            - mountPath: /vault/userconfig/tls
              name: tls
              readOnly: true
          dataStorage:
            enabled: true
            size: 10Gi
            storageClass: standard
          auditStorage:
            enabled: true
            size: 10Gi
            storageClass: standard
          readinessProbe:
            enabled: true
            path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
          service:
            type: NodePort
            nodePort: 30820
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: vault.nuco-dev.fr
            tls:
              - hosts:
                  - vault.nuco-dev.fr
                secretName: vault-tls
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
