---
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"
metadata:
  name: nico-main-cluster
spec:
  teamId: nico
  postgresql:
    version: "14"
  volume:
    size: 10Gi
    storageClass: local-path
  numberOfInstances: 1
  users:
    nico.nico: []
    keycloak.keycloak: []
  databases:
    nico: nico.nico
    keycloak: keycloak.keycloak

