---
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "nico"
  namespace: "postgres"
  labels:
    team: nico

spec:
  teamId: "nico"
  postgresql:
    version: "14"
  numberOfInstances: 2
  volume:
    size: "10Gi"
    storageClass: "local-path"
  users:
    nico: []
    keycloak.keycloak: []
  databases:
    nico: nico
    keycloak: keycloak.keycloak
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
